//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF2_FokavinMMO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int id { get; set; }
        public Nullable<int> Rarityid { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> CharacterClassid { get; set; }
        public string Name { get; set; }
    
        public virtual CharacterClass CharacterClass { get; set; }
        public virtual Rarity Rarity { get; set; }
    }
}
